on:
  push: {}
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to gchr.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        if: ${{ github.event_name != 'pull_request' }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/gridgain-helper
      - name: build and push
        uses: docker/build-push-action@v4
        with:
          context: helper
          file: helper/Dockerfile
          cache-from: type=gha
          cache-to: type=gha
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          tags: ${{ steps.docker_meta.outputs.tags }}